[build]
builder = "dockerfile"

[deploy]
startCommand = "/app/start.sh" 
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Add health check
healthcheckPath = "/"
healthcheckTimeout = 100